### ISSUE TITLE
Published version in npm is sleepless/passport-stormpath ?

### ISSUE THREAD

**Issue by doublerebel** [stormpath/passport-stormpath#20]
Hello,

I installed passport-stormpath from npm just now, and it looks like a fork has been published over the official version?

Here is the contents of the `package.json`:
```json
{
  "name": "passport-stormpath",
  "version": "1.0.3",
  "description": "Authentication strategy for Stormpath",
  "keywords": [
    "passport",
    "stormpath"
  ],
  "repository": {
    "type": "git",
    "url": "git://github.com/sleeplessinc/passport-stormpath.git"
  },
  "bugs": {
    "url": "http://github.com/sleeplessinc/passport-stormpath/issues"
  },
  "author": {
    "name": "Joe Hitchens",
    "email": "joe@sleepless.com",
    "url": "http://sleepless.com"
  },
  "licenses": [
    {
      "type": "MIT",
      "url": "http://www.opensource.org/licenses/MIT"
    }
  ],
  "main": "./lib",
  "dependencies": {
    "passport-strategy": "1.x.x"
  },
  "_id": "passport-stormpath@1.0.3",
  "dist": {
    "shasum": "659e3275c254c6c22b19e577c6f8c23caf96183d",
    "tarball": "http://registry.npmjs.org/passport-stormpath/-/passport-stormpath-1.0.3.tgz"
  },
  "_from": "passport-stormpath@1.0.3",
  "_npmVersion": "1.2.11",
  "_npmUser": {
    "name": "sleeplessinc",
    "email": "joe@sleepless.com"
  },
  "maintainers": [
    {
      "name": "sleeplessinc",
      "email": "joe@sleepless.com"
    }
  ],
  "directories": {},
  "_shasum": "659e3275c254c6c22b19e577c6f8c23caf96183d",
  "_resolved": "http://registry.npmjs.org/passport-stormpath/-/passport-stormpath-1.0.3.tgz",
  "readme": "ERROR: No README data found!",
  "homepage": "https://github.com/sleeplessinc/passport-stormpath"
}
```

Which matches with [sleeplessinc/passport-stormpath](//github.com/sleeplessinc/passport-stormpath).  Unfortunately this published fork requires [sleepless-stormpath](//www.npmjs.com/package/sleepless-stormpath) package which is not included as a dependency.

Maybe this is a bug in npm or sleepless accidentally published a private package.  Odd because [the npm page](https://www.npmjs.com/package/passport-stormpath) only shows 0.2.3. @npm  @sleeplessinc ?

**Comment by sleeplessinc** [comment]
Well the confusion probably comes from the fact that Sleepless created a
rudimentary version of the stormpath code for node, and put it into github
with a typical/likely repo name for it.  Sleepless did not get involved in
anyway with their official version though, so maybe you followed a bad/old
link or something.

Sorry, can't help you beyond that.  Good luck.  Ask the stormpath guys for
the proper package name?

j.h.



On Sun, Jan 25, 2015 at 2:49 PM, Charles Phillips <notifications@github.com>
wrote:

> Hello,
>
> I installed passport-stormpath from npm just now, and it looks like a fork
> has been published over the official version?
>
> Here is the contents of the package.json:
>
> {
>   "name": "passport-stormpath",
>   "version": "1.0.3",
>   "description": "Authentication strategy for Stormpath",
>   "keywords": [
>     "passport",
>     "stormpath"
>   ],
>   "repository": {
>     "type": "git",
>     "url": "git://github.com/sleeplessinc/passport-stormpath.git"
>   },
>   "bugs": {
>     "url": "http://github.com/sleeplessinc/passport-stormpath/issues"
>   },
>   "author": {
>     "name": "Joe Hitchens",
>     "email": "joe@sleepless.com",
>     "url": "http://sleepless.com"
>   },
>   "licenses": [
>     {
>       "type": "MIT",
>       "url": "http://www.opensource.org/licenses/MIT"
>     }
>   ],
>   "main": "./lib",
>   "dependencies": {
>     "passport-strategy": "1.x.x"
>   },
>   "_id": "passport-stormpath@1.0.3",
>   "dist": {
>     "shasum": "659e3275c254c6c22b19e577c6f8c23caf96183d",
>     "tarball": "http://registry.npmjs.org/passport-stormpath/-/passport-stormpath-1.0.3.tgz"
>   },
>   "_from": "passport-stormpath@1.0.3",
>   "_npmVersion": "1.2.11",
>   "_npmUser": {
>     "name": "sleeplessinc",
>     "email": "joe@sleepless.com"
>   },
>   "maintainers": [
>     {
>       "name": "sleeplessinc",
>       "email": "joe@sleepless.com"
>     }
>   ],
>   "directories": {},
>   "_shasum": "659e3275c254c6c22b19e577c6f8c23caf96183d",
>   "_resolved": "http://registry.npmjs.org/passport-stormpath/-/passport-stormpath-1.0.3.tgz",
>   "readme": "ERROR: No README data found!",
>   "homepage": "https://github.com/sleeplessinc/passport-stormpath"
> }
>
> Which matches with sleeplessinc/passport-stormpath
> <//github.com/sleeplessinc/passport-stormpath>. Unfortunately this
> published fork requires sleepless-stormpath
> <//www.npmjs.com/package/sleepless-stormpath> package which is not
> included as a dependency.
>
> Maybe this is a bug in npm or sleepless accidentally published a private
> package. Odd because the npm page
> <https://www.npmjs.com/package/passport-stormpath> only shows 0.2.3. @npm
> <https://github.com/npm> @sleeplessinc <https://github.com/sleeplessinc> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stormpath/passport-stormpath/issues/20>.
>



-- 

*Joe Hitchens*

Sleepless Software Inc.
3489 Locker Road SE, Suite 200
Port Orchard, WA 98366
Sleepless.com <http://sleepless.com>

**Comment by doublerebel** [comment]
@sleeplessinc Thanks for the fast reply!  Did you ever publish your package to npm?  Perhaps since your versioning scheme starts with 1.x, the npm repo is returning that instead of the newer 0.2.3 from Stormpath.

**Comment by rdegges** [comment]
Hmm, I'm not really able to reproduce this. On npm, passport-stormpath shows as being published by us: https://www.npmjs.com/package/passport-stormpath

Not sure how you're installing their version oO

**Comment by doublerebel** [comment]
@rdegges It looks like the old version of passport-stormpath is originally published at http://registry.npmjs.org/passport-stormpath/-/passport-stormpath-1.0.3.tgz .  I checked again, it wasn't the `npm install`, that works as expected.  When I do `npm update` and have my package.json allowing `>=0.2.3`, npm updates to the 1.0.3 package.  Perhaps it should be unpublished?

**Comment by rdegges** [comment]
oO

Interesting! This seems like more of an npm bug to be honest: they should never knowingly let someone install a package that is not current -- that seems pretty crazy to me.

As a workaround though, the unpublish would likely help.

Sorry for the trouble!

**Comment by doublerebel** [comment]
No problem, thanks for helping me work through this on a Sunday :)

Running `npm outdated` with 1.0.3 installed correctly shows 0.2.3 as being the latest version; running `npm outdated` with 0.2.3 installed does not list the package (indicating 0.2.3 is current).  You're right, this should be filed with @npm against `npm update`.
